server:
  port: 8000
  http2:
    enabled: true
  context-path: /
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: static_route
          uri: http://localhost:9527
          predicates:
          - Path=/**
        - id:  apiuser
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://user-service
          predicates:
          # 重点！转发该路径！,/userapi/**,
          - Path=/userapi/**
          # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
          #而不是我们期望的去掉userapi，只保留**部分
          filters:
          - StripPrefix=1
        - id:  api2user
          uri: lb://user-service
          predicates:
          - Path=/userapi2/**
          filters:
          - StripPrefix=1
eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
      defaultZone: http://eurekaserver1:8100/eureka,http://eurekaserver2:8200/eureka,http://eurekaserver3:8300/eureka