spring:
  application:
    name: cloud-server
    profiles: eurekaserver2
server:
  port: 1002

eureka:
  instance:
    hostname: eurekaserver2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:1001/eureka/