spring:
    profiles: eurekaserver1
server:
  port: 8100

eureka:
  instance:
    hostname: eurekaserver1
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:8200/eureka,http://eurekaserver3:8300/eureka