spring:
  application:
    name: cloud-server
    profiles: eurekaserver1
server:
  port: 1001

eureka:
  instance:
    hostname: eurekaserver1
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:1002/eureka/